/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Import': '导入',
    'World Map': '世界地图',
    'World α': '世界 α',
    'Play Again': '重玩',
    'manager': '管理',
    '“A New Age”': '“新时代”',
    '“Before Life”': '“在生命之前”',
    '“Conquer the World”': '“征服世界”',
    '“Expanding Civilization”': '“扩张文明”',
    '“Market Crash” obstacle': '“崩盘”的障碍',
    '“The Beginning”': '“开端”',
    'Amount': '数量',
    'and': '和',
    'Save': '保存',
    'Saving': '保存中',
    'solider': '士兵',
    'spiritual power': '精神力量',
    'territory': '领土',
    'points': '点',
    'The Singularity': '奇点',
    'this one over here': '这儿有一个',
    'Total': '总计',
    'You might have noticed the word "World α" above the point counter. What does it mean?': '你可能已经注意到“世界α”这个词在点数计数器上面。这是什么意思?',
    'HARD RESET': '硬重置',
    'HARD RESET THE GAME': '硬重置游戏',
    'Layer / Resource': '层 / 资源',
    'Layer Breakdown': '层分解',
    'layer.': '层.',
    'Made some rebalancing to the early game.': '重新平衡了早期的游戏。',
    'magic spells': '魔法',
    'milestones.': '里程碑。',
    'multiplier.': '倍数.',
    'point of singularity': '奇点',
    'rebuyables.': '可回购商品。',
    'Replaced two of the last': '替换了最后两个',
    'Close': '关闭',
    'Best': '最好',
    'banking': '银行业',
    'bankings': '银行业',
    'Current endgame': '当前的残局',
    'Display': '显示',
    'Export save to clipboard': '导出存档到剪贴板',
    'Export to clipboard': '导出到剪贴板',
    'Game Changelog': '更新日志',
    'Fixed the': '修复',
    'Gameplay': '游戏玩法',
    'Hotkeys': '快捷键',
    'Hotkeys should work even if you don\'t unlock that layer yet.': '即使您尚未解锁该层，热键也应该起作用。',
    'Keep Going': '继续',
    'Import save': '导入存档',
    'Instant save': '即时保存',
    'It took you {{formatTimeLong(player.timePlayed)}} to reach the singularity point.': '您花了{{formatTimeLong(player.timePlayed)}}到达奇点。',
    'The point of singularity has been reached. Your civilization did not make it through.': '达到了奇点。 您的文明没有成功。',
    'This exists. Posibly buggy. Very unbalanced. Need suggestions.': '这是存在的。可能是Bug。很不平衡。需要建议。',
    'procedural world generation': '程序世界生成',
    'Congratulations! You have reached the point of singularity and beaten this game, but for now...': '恭喜你！ 您已经达到了奇点并击败了该游戏，但是现在...',
    'buildings': '建筑',
    'builder': '建设者',
    'before that.': '在那之前。',
    'with': '和',
    'to the': '到',
    'knowledge': '知识',
    'Land and Jobs Management': '土地和工作管理',
    'layer (didn\'t have anything for now).': '层（暂时没有任何内容）。',
    'Made various UI adjustments.': '进行了各种UI调整。',
    'and total': '和累计',
    'and the': '和',
    'and renamed the': '并改名为',
    '. Any civilization go past this point did not make it through.': '。 任何文明都超过了这一点并没有实现。',
    'Make more various UI adjustments.': '进行更多各种UI调整。',
    'C: Reset for coins': 'C：重置硬币',
    'not functioning as intended.': '不能按预期运行。',
    'The Dynas Tree': '分叉树',
    'I understand the consequences, do it!': '我了解后果，继续！',
    'This is a dangerous process! You\'ll lose all of your progress if you continue doing this!': '这是一个危险的过程！ 如果继续这样做，您将失去所有游戏进度！',
    'Are you sure you want to hard reset?': '您确定要硬重置吗？',
    'Coins': '硬币',
    'Points': '点数',
    'Reset for': '重置得到',
    "You have": "你有",
    'coins': '硬币',
    'You have at best {{formatWhole(player[layer].best)}} {{layers[layer].resource}}.': '你的最佳是 {{formatWhole(player[layer].best)}} {{layers[layer].resource}}.',
    'You have made a total of {{formatWhole(player[layer].total)}} {{layers[layer].resource}}.': '您总共制作了 {{formatWhole(player[layer].total)}} {{layers[layer].resource}}.',
    '': '',
    "Autosave: ": "自动保存: ",
    'Autosave: {{ player.autosave?"ENABLED":"DISABLED" }}': '自动保存: {{ player.autosave?"启用":"禁用" }}',
    'Autosave: {{ player.autosave?"ON":"OFF" }}': '自动保存: {{ player.autosave?"打开":"关闭" }}',
    'Boosts points generation based on your total coin count.': '根据您的总硬币数提高点数的产生。',
    'Currently': '当前',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    'Added some new things to the layers before that.': '在此之前，在图层中添加了一些新内容。',
    'Fixed some bugs related to progressing and save importing.': '修复了一些与进度和保存导入有关的错误。',
    'Fix the number formatting not working correctly over e1,000 bug.': '修复了数字格式在e1,000错误中无法正常工作的问题。',
    'Added a concept of a modal. It should appear if you have an error along with details of it for easier reporting.': '添加了模态的概念。 如果您有错误及其详细信息，则应该显示该错误，以便于报告。',
    '☀️ The Dynas Tree v0.': '☀️ 分叉树 v0.',
    'Added': '增加',
    'Added more': '增加了更多的',
    'Added more mechanics to the': '增加了更多的机制',
    'Added spoiler boxes to the changelog, which should be looking like': '将扰流器框添加到了更新日志中，看起来应该像',
    'Added the achievements tab. It\'s just a placeholder for now. Or there won\'t be any achievements in the game at all. We\'ll see...': '添加了成就标签。 现在只是一个占位符。 否则，游戏中根本不会有任何成就。 走着瞧...',

    //原样
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    'You have {{formatWhole(tmp.layerAmt[layer])}} ': '你有 {{formatWhole(tmp.layerAmt[layer])}} ',
    'You have {{formatWhole(tmp.layerAmt[layer])}} ': '你有 {{formatWhole(tmp.layerAmt[layer])}} ',
    'Offline Production: {{ player.offlineProd?"ENABLED":"DISABLED" }}': '离线生产: {{ player.offlineProd?"启用":"禁用" }}',
    "You have played this game for ": "你累计玩了 ",
    " made a total of ": "共计",
    " played this game for ": " 玩了这个游戏 ",
    "Migrated to The Modding Tree v": "迁移到改装树v",
    "Offline Prod: ": "离线产品：",
    "Option Tab Flavor: ": "选项标签风格：",
    "High-Quality Tree: ": "高质量的树:",
    "Unfortunately, this world does not have any achievements.": "遗憾的是，这个世界没有任何成就。",
    "Theme: ": "主题: ",
    "Show Milestones: ": "显示里程碑：",
    "Tree Quality:": "树品质：",
    "Tree Menu Flavor:": "树菜单风格：",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    " ": "",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    "\n": "",
    "Achievements": "成就",
    "Options": "选项",
    "Statistics": "统计",
    "Offline Time": "离线时间",
    " The Dynas Tree v0.": " 分叉树 v0.",
    "ENABLED": "启用",
    "ON": "打开",
    "DEFAULT": "默认",
    "Default": "默认",
    "REMADE": "改版",
    "CLASSIC": "经典",
    "ALWAYS": "总是",
    "AUTOMATION": "自动化",
    "INCOMPLETE": "残缺",
    "PERFORMANCE": "性能",
    "TOPBAR": "顶栏",
    "OFF": "关闭",
    "AQUA": "水族",
    "NEVER": "从不",
    "AUTOMATI": "自动",
    "QUALITY": "质量",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^x?\d+(\.\d+)?[A-Za-z%]{0,2}(\s.C)?\s*$/, //12.34K,23.4 °C
    /^x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /^\s*$/, //纯空格
    /^\d+(\.\d+)?[A-Za-z]{0,2}.?\(?([+\-]?(\d+(\.\d+)?[A-Za-z]{0,2})?)?$/, //12.34M (+34.34K
    /^(\d+(\.\d+)?[A-Za-z]{0,2}\/s)?.?\(?([+\-]?\d+(\.\d+)?[A-Za-z]{0,2})?\/s\stot$/, //2.74M/s (112.4K/s tot
    /^\d+(\.\d+)?(e[+\-]?\d+)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?$/, //2.177e+6 (+4.01+4
    /^(\d+(\.\d+)?(e[+\-]?\d+)?\/s)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?\/s\stot$/, //2.177e+6/s (+4.01+4/s tot
];
var cnExcludePostfix = [
    /:?\s*x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /:?\s*x?\d+(\.\d+)?[A-Za-z]{0,2}$/, //: 12.34K, x1.5
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^(.+)You have played this for: (.+)$/, '你已经玩了：'],
    [/^你累计玩了 (.+) hours, (.+) minutes and (.+) seconds.\n(.+)$/, '你累计玩了 $1小时 $2分 $3秒 的游戏。'],
    [/^Next at (.+) points$/, '接下来在$1点'],
    [/^Cost: (.+) coins\n(.+)$/, '费用：$1个硬币'],
    [/^Generates (.+) points every second.$/, '每秒产生$1点。'],
    [/^(.+)Offline Time$/, '离线时间'],
    [/^(.+)Offline Time: {{formatTime(player.offTime.remain)}}$/, '离线时间: {{formatTime(player.offTime.remain)}}'],
    [/^(.+)Dev Speed: {{format(player.devSpeed)}}×$/, '开发速度: {{format(player.devSpeed)}}×'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);